version: "3.1"
services:
  mysql:
    image: mysql:5.7
    container_name: larp-mysql
    working_dir: /application
    command: --general-log=1 --general-log-file=/tmp/my.log
    volumes:
      - mysql-data:/var/lib/mysql
    env_file:
      - .env
    ports:
      - "3304:3306"

volumes:
  mysql-data:
